### ISSUE TITLE
Add save paramenter

### ISSUE THREAD

**Issue by dnsBlah** [ctomkow/swITch#5]
Currently it's impossible to save the configuration to the device
I figured with the netmiko that this works, at least on cisco_ios
`dev.save_config(cmd="write", confirm=True)`

Not sure how to implement it on your script to support other OS's but adding param args.saveConfig and before the dev.disconnect
```
if saveConfig:
    dev.save_config(cmd="write", confirm=True)
```

**Comment by ctomkow** [comment]
Hi dnsBlah.

I will take a look.

I know historically I use to just have a ```write mem``` for IOS devices as the last item in the cli file when using the --cmd flag, as a work around. That is definitely a hack though.

Also, when I implemented the --set flag, which executes netmiko's ```send_config_set()``` function, I missed the obvious saving of config. The saving of config should be implemented in the --set flag context.

**Comment by ctomkow** [comment]
Regarding the save_config function ```dev.save_config(cmd="write", confirm=True)```.

It seems like netmiko implements the ```save_config()``` function for each device type. Since my devices map to netmiko's devices, calling ```save_config``` just before disconnecting as you mention should work well.

**Comment by ctomkow** [comment]
Current WIP on branch, save_config https://github.com/ctomkow/swITch/tree/save_config. It currently is working for Juniper, Cisco IOS, and HP. Need to have it work for Sentry PDU's and PaloAlto's.

The opinionated idea is that the ```--set``` flag is provided a set of configuration commands only (single line or file to read). It then applies the configuration to the device and saves the configuration right after.

e.g.
```swITch.py -eva auth.txt -i 10.10.10.10,cisco_ios -s "logging host 10.50.50.50"```

If this is not desired, then the ```--cmd``` flag should be used to provide any type of cli commands in any order as needed.

**Comment by ctomkow** [comment]
I merged my branch into the master branch. 902455364a2ee5e4a6564aa94310f40ecf2b2f35 I tested it for all the devices supported and should be working correctly. If any issues are noticed, please reply back about the new issue. Also, created new release [0.1.7](https://github.com/ctomkow/swITch/releases/tag/v0.1.7)
